basePath: /api/v1
definitions:
  main.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  main.Todo:
    properties:
      userID:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  title: Backend API Service
  version: 1.0.0
paths:
  /todo/delete:
    delete:
      consumes:
      - application/json
      description: delete
      parameters:
      - description: user's ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Todo DELETE Example
  /todo/get:
    get:
      description: check gateway and account service health :)
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HTTPError'
      summary: Todo GET Example
  /todo/post:
    post:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: The input todo struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Todo POST Example
  /todo/put:
    put:
      consumes:
      - application/json
      description: put
      parameters:
      - description: The input todo struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Todo PUT Example
securityDefinitions:
  ApiKeyAuth (JWT):
    in: header
    name: AccessToken
    type: apiKey
swagger: "2.0"
